language: node_js
node_js:
  - 16
script:
  - npm run test
  - npm run build
deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main